# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minerals', '0002_auto_20171106_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineral',
            name='group',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
