# Generated by Django 2.0.1 on 2018-02-12 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minerals', '0003_mineral_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mineral',
            options={},
        ),
    ]
