# Generated by Django 2.0.1 on 2018-02-12 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minerals', '0004_auto_20180212_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mineral',
            options={'ordering': ['name']},
        ),
    ]
